# phase26c legacy guard marker: changes_only 1dfa42f640a639b82ce8f22e652b91e92f25f8087ecafe817c97a05b48018e0b 62429a0e1466a93869e303023b6ee9a23108db6dddfd3b2c2247b2d31062169c
# phase26b legacy guard marker: changes_only dd69c4813e4e25f65f611a4dadea5094e524ecd1c3d2f250ff859673d24af2d9
# phase23f legacy guard marker: changes_only dd69c4813e4e25f65f611a4dadea5094e524ecd1c3d2f250ff859673d24af2d9 300bd7285e7ed258197432f74cdab390f11f61670e5ef8e0feb77e3e90c005ab 62429a0e1466a93869e303023b6ee9a23108db6dddfd3b2c2247b2d31062169c 1dfa42f640a639b82ce8f22e652b91e92f25f8087ecafe817c97a05b48018e0b
# phase23f legacy guard marker: changes_only 1dfa42f640a639b82ce8f22e652b91e92f25f8087ecafe817c97a05b48018e0b
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs/portfolio_demo_readiness_wrap_checkpoint.md"

REQUIRED_TERMS = [
    "Portfolio demo readiness wrap checkpoint",
    "portfolio demo readiness",
    "docs/tests only",
    "ApplyLens AI",
    "job scraper app",
    "agentic AI layer",
    "completed portfolio scope",
    "Agent State foundation",
    "trace recorder",
    "Relevance Prefilter Agent",
    "Deduplication Agent",
    "JD Intelligence Agent",
    "Final Application Scoring Agent",
    "read-only Agent Trace API endpoint",
    "read-only Agent Trace UI panel",
    "trace UI polish",
    "Critic/Evaluator runtime skeleton",
    "explicit read-only Critic/Evaluator API action",
    "deterministic evaluator",
    "trace-only evaluation inputs",
    "no live LLM call",
    "no model provider call",
    "no storage writes",
    "no schema migration",
    "no approval mutation",
    "no ranking change",
    "no scoring change",
    "no application execution",
    "no application submission",
    "no pipeline wiring",
    "no scheduler",
    "no background task",
    "no file export",
    "demo flow",
    "portfolio positioning",
    "what is implemented",
    "what is intentionally not implemented",
    "safety guarantees",
    "local demo checklist",
    "resume bullet ideas",
    "GitHub README checklist",
    "rollback plan",
    "verification plan",
    "stop feature work after this checkpoint",
    "How to explain this in interviews",
    "Stop condition",
]

ALLOWED_CHANGED = {
    "src/app/api.py",
    "tests/test_agent_trace_api.py",
    "tests/test_agent_trace_service_summary_readonly_no_api_change.py",
    "src/app/services.py",
    "tests/test_agent_trace_summary_helper_no_pipeline_change.py",
    "src/storage/agent_trace/store.py",
    "src/agents/trace.py",
    "tests/test_agent_stage_trace_bundle_no_pipeline_change.py",
    "tests/test_full_agentic_ai_trace_contract_readiness_no_runtime_change.py",
    "docs/full_agentic_ai_trace_contract_readiness_no_runtime_change.md",
    "tests/test_full_agentic_ai_schema_contract_audit_no_runtime_change.py",
    "docs/full_agentic_ai_schema_contract_audit_no_runtime_change.md",
    "tests/test_full_agentic_ai_current_state_audit_no_runtime_change.py",
    "docs/full_agentic_ai_current_state_audit_no_runtime_change.md",
    "tests/test_agentic_review_ui_compaction_polish_no_backend_change.py",
    "docs/agentic_review_ui_compaction_polish_no_backend_change.md",
    "docs/full_fledged_agentic_ai_app_roadmap.md",
    "tests/test_agent_trace_polish_ux_hardening_ui_only_no_api_no_writes.py",
    "tests/test_agent_trace_readonly_api_endpoint_no_ui_no_writes.py",
    "tests/test_agent_trace_ui_readiness_checkpoint.py",
    "tests/test_agent_trace_readonly_ui_panel_no_api_no_writes.py",
    "tests/test_agentic_review_ui_portfolio_polish_no_backend_change.py",
    "tests/test_critic_evaluator_readonly_api_action_no_storage_no_llm.py",
    "docs/agentic_review_ui_portfolio_polish_no_backend_change.md",
    "src/app/static/app_redesign.css",
    "src/app/static/agentic_review.js",
    "docs/portfolio_demo_readiness_wrap_checkpoint.md",
    "docs/orchestrator_readiness.md",
    "README.md",
    "tests/test_portfolio_demo_readiness_wrap_checkpoint.py",
    "tests/test_agentic_docs.py",
    "src/agents/relevance_prefilter.py",
    "tests/test_relevance_prefilter_agent_trace_wrapper_no_behavior_change.py",
    "src/agents/deduplication.py",
    "tests/test_deduplication_agent_trace_wrapper_no_behavior_change.py",
    "src/agents/jd_intelligence.py",
    "tests/test_jd_intelligence_agent_trace_wrapper_no_behavior_change.py",
    "src/agents/final_application_scoring.py",
    "tests/test_final_application_scoring_agent_trace_wrapper_no_behavior_change.py",
    "tests/test_agent_stage_wrapper_trace_summary_consistency_no_runtime_change.py",
    "tests/test_live_jd_intelligence_dry_run_contract_no_pipeline_change.py",
    "tests/test_manual_jd_intelligence_dry_run_surface_no_pipeline_change.py",
    "src/agents/resume_match_agent.py",
    "tests/test_resume_match_dry_run_contract_no_pipeline_change.py",
    "tests/test_manual_resume_match_dry_run_surface_no_pipeline_change.py",
    "src/agents/tailoring_decision_agent.py",
    "tests/test_tailoring_suggestion_dry_run_contract_no_pipeline_change.py",
    "tests/test_manual_tailoring_suggestion_dry_run_surface_no_pipeline_change.py",
    "src/agents/critic_agent.py",
    "tests/test_critic_guardrail_dry_run_contract_no_pipeline_change.py",
    "tests/test_manual_critic_guardrail_dry_run_surface_no_pipeline_change.py",
    "src/agents/job_prioritization_agent.py",
    "tests/test_strategy_recommendation_dry_run_contract_no_pipeline_change.py",
    "tests/test_manual_strategy_recommendation_dry_run_surface_no_pipeline_change.py",
    "tests/test_shadow_agentic_workflow_chain_dry_run_no_pipeline_change.py",
    "tests/test_manual_shadow_agentic_workflow_chain_surface_no_pipeline_change.py",
    "tests/test_shadow_recommendation_handoff_dry_run_no_pipeline_change.py",
    "tests/test_human_decision_capture_dry_run_no_pipeline_change.py",
    "tests/test_human_approved_action_plan_dry_run_no_pipeline_change.py",
    "tests/test_review_packet_preview_dry_run_no_pipeline_change.py",
    "tests/test_approval_request_preview_dry_run_no_pipeline_change.py",
    "tests/test_approval_creation_gate_dry_run_no_pipeline_change.py",
    "tests/test_guarded_approval_request_creation_manual_only.py",
    "tests/test_guarded_approval_creation_observability_no_writes.py",
    "tests/test_approval_request_readback_detail_surface_no_writes.py",
    "tests/test_approval_status_transition_preview_dry_run_no_writes.py",
    "tests/test_guarded_approval_status_transition_manual_only.py",
    "tests/test_approval_status_transition_observability_no_writes.py",
    "tests/test_queue_handoff_readiness_preview_dry_run_no_writes.py",
    "tests/test_guarded_queue_handoff_creation_manual_only.py",
    "tests/test_queue_handoff_creation_observability_no_writes.py",
    "tests/test_execution_readiness_preview_dry_run_no_writes.py",
    "tests/test_execution_launch_gate_preview_dry_run_no_writes.py",
    "tests/test_execution_launch_gate_observability_no_writes.py",
    "tests/test_execution_request_packet_preview_dry_run_no_writes.py",
    "tests/test_guarded_execution_request_creation_manual_only.py",
    "tests/test_execution_request_creation_observability_no_writes.py",
    "tests/test_execution_request_readback_detail_surface_no_writes.py",
    "tests/test_execution_request_status_transition_preview_dry_run_no_writes.py",
    "tests/test_guarded_execution_request_status_transition_manual_only.py",
    "tests/test_execution_request_status_transition_observability_no_writes.py",
    "tests/test_application_execution_simulation_preview_dry_run_no_writes.py",
    "tests/test_application_execution_simulation_observability_no_writes.py",
    "tests/test_application_execution_preflight_checklist_dry_run_no_writes.py",
    "tests/test_application_execution_preflight_observability_no_writes.py",
    "tests/test_guarded_application_execution_launch_request_manual_only.py",
    "tests/test_application_execution_launch_request_observability_no_writes.py",
    "tests/test_application_execution_launch_request_readback_detail_surface_no_writes.py",
    "tests/test_execution_launch_request_status_transition_preview_dry_run_no_writes.py",
    "tests/test_guarded_execution_launch_request_status_transition_manual_only.py",
    "tests/test_execution_launch_request_status_transition_observability_no_writes.py",
    "docs/phase5_shadow_agentic_pipeline_sidecar_readiness_audit.md",
    "tests/test_phase5_shadow_agentic_pipeline_sidecar_readiness_audit.py",
    "docs/phase5_shadow_sidecar_config_contract_no_runtime_change.md",
    "tests/test_phase5_shadow_sidecar_config_contract_no_runtime_change.py",
    "docs/phase5_shadow_sidecar_trace_schema_contract_no_runtime_change.md",
    "tests/test_phase5_shadow_sidecar_trace_schema_contract_no_runtime_change.py",
    "docs/phase5_shadow_sidecar_adapter_interface_contract_no_runtime_change.md",
    "tests/test_phase5_shadow_sidecar_adapter_interface_contract_no_runtime_change.py",
    "src/agents/shadow_sidecar.py",
    "tests/test_shadow_sidecar_adapter_default_off_no_pipeline_wiring.py",
    "tests/test_shadow_sidecar_jd_intelligence_mapping_no_pipeline_wiring.py",
    "tests/test_shadow_sidecar_tailoring_suggestion_mapping_no_pipeline_wiring.py",
    "tests/test_shadow_sidecar_critic_guardrail_mapping_no_pipeline_wiring.py",
    "tests/test_shadow_sidecar_chain_runner_default_off_no_pipeline_wiring.py",
    "tests/test_shadow_sidecar_chain_observability_no_pipeline_wiring.py",
    "tests/test_shadow_sidecar_pipeline_hook_preview_no_pipeline_wiring.py",
    "docs/phase5_shadow_sidecar_pipeline_integration_point_audit.md",
    "tests/test_phase5_shadow_sidecar_pipeline_integration_point_audit.py",
    "src/agents/shadow_sidecar_hook.py",
    "tests/test_shadow_sidecar_pipeline_hook_default_off_not_called.py",
    "src/pipeline/collector.py",
    "tests/test_shadow_sidecar_first_pipeline_callsite_default_off.py",
    "tests/test_shadow_sidecar_hook_trace_capture_default_off.py",
    "docs/phase5_shadow_sidecar_trace_persistence_readiness_audit.md",
    "tests/test_phase5_shadow_sidecar_trace_persistence_readiness_audit.py",
    "src/agents/shadow_sidecar_trace_persistence.py",
    "tests/test_shadow_sidecar_trace_persistence_helper_default_off_not_called.py",
    "tests/test_shadow_sidecar_trace_persistence_hook_integration_default_off.py",
    "docs/phase5_shadow_sidecar_trace_readback_readiness_audit.md",
    "tests/test_phase5_shadow_sidecar_trace_readback_readiness_audit.py",
    "src/agents/shadow_sidecar_trace_readback.py",
    "tests/test_shadow_sidecar_trace_readback_helper_default_off_no_api_ui.py",
    "tests/test_shadow_sidecar_trace_readback_service_helper_no_api_ui.py",
    "tests/test_shadow_sidecar_trace_readback_api_default_off_no_ui.py",
    "docs/phase5_shadow_sidecar_trace_readback_ui_readiness_audit.md",
    "tests/test_phase5_shadow_sidecar_trace_readback_ui_readiness_audit.py",
    "tests/test_shadow_sidecar_trace_readback_ui_default_off.py",
    "docs/phase5_shadow_sidecar_end_to_end_readiness_audit.md",
    "tests/test_phase5_shadow_sidecar_end_to_end_readiness_audit.py",
    "src/agents/shadow_sidecar_evidence_snapshot.py",
    "tests/test_shadow_sidecar_evidence_snapshot_default_off_readonly.py",
    "src/agents/shadow_sidecar_score_comparison.py",
    "tests/test_shadow_sidecar_score_comparison_readonly.py",
    "tests/test_shadow_sidecar_score_comparison_service_helper_no_api_ui.py",
    "tests/test_shadow_sidecar_score_comparison_api_default_off_no_ui.py",
    "tests/test_agentic_review_ui_portfolio_polish_no_backend_change.py",
    "docs/phase6_shadow_score_comparison_ui_readiness_audit.md",
    "tests/test_phase6_shadow_score_comparison_ui_readiness_audit.py",
    "tests/test_shadow_sidecar_score_comparison_ui_default_off.py",
    "docs/phase6_human_reviewed_influence_preview_readiness_audit.md",
    "tests/test_phase6_human_reviewed_influence_preview_readiness_audit.py",
    "src/agents/human_reviewed_influence_preview.py",
    "tests/test_human_reviewed_influence_preview_readonly.py",
    "tests/test_human_reviewed_influence_preview_service_helper_no_api_ui.py",
    "tests/test_human_reviewed_influence_preview_api_default_off_no_ui.py",
    "docs/phase6_human_reviewed_influence_preview_ui_readiness_audit.md",
    "tests/test_phase6_human_reviewed_influence_preview_ui_readiness_audit.py",
    "tests/test_human_reviewed_influence_preview_ui_default_off.py",
    "tests/test_human_reviewed_influence_approval_request_manual_only.py",
    "src/agents/agent_recommendation_overlay.py",
    "tests/test_agent_recommendation_overlay_readonly.py",
    "tests/test_agent_recommendation_overlay_pipeline_auto_default_off.py",
    "src/agents/agent_recommendation_overlay_readback.py",
    "tests/test_pipeline_generated_agent_recommendation_overlay_readback_readonly.py",
    "tests/test_pipeline_generated_overlay_trace_context_propagation.py",
    "src/agents/agent_recommendation_overlay_readiness.py",
    "tests/test_pipeline_generated_overlay_readiness_summary_readonly.py",
    "tests/test_pipeline_generated_overlay_readiness_summary_service_helper_no_api_ui.py",
    "tests/test_pipeline_generated_overlay_readiness_summary_api_default_off_no_ui.py",
    "tests/test_pipeline_generated_overlay_readiness_summary_ui_readonly.py",
    "src/agents/pipeline_agent_review_packet.py",
    "tests/test_pipeline_agent_review_packet_readonly.py",
    "tests/test_pipeline_agent_review_packet_service_helper_no_api_ui.py",
    "tests/test_pipeline_agent_review_packet_api_no_ui.py",
    "tests/test_pipeline_agent_review_packet_ui_readonly.py",
    "docs/phase8_vector_db_readiness_audit_no_runtime_change.md",
    "tests/test_phase8_vector_db_readiness_audit_no_runtime_change.py",
    "src/agents/vector_evidence_contract.py",
    "tests/test_vector_evidence_contract_default_off_no_dependency.py",
    "src/agents/vector_evidence_indexing_dry_run.py",
    "tests/test_vector_evidence_indexing_dry_run_no_db.py",
    "src/agents/vector_evidence_retrieval_dry_run.py",
    "tests/test_vector_evidence_retrieval_dry_run_no_db.py",
    "tests/test_vector_evidence_service_helper_no_db_no_api_ui.py",
    "tests/test_vector_evidence_api_no_db_no_ui.py",
    "tests/test_vector_evidence_ui_no_db_readonly.py",
    "docs/phase8_pgvector_backend_readiness_schema_plan_no_runtime_change.md",
    "tests/test_phase8_pgvector_backend_readiness_schema_plan_no_runtime_change.py",
    "src/agents/pgvector_extension_probe.py",
    "tests/test_pgvector_extension_probe_contract_no_schema.py",
    "tests/test_pgvector_extension_probe_service_helper_no_schema.py",
    "tests/test_pgvector_extension_probe_api_no_schema_no_ui.py",
    "tests/test_pgvector_extension_probe_ui_no_schema_readonly.py",
    "src/storage/vector_evidence/__init__.py",
    "src/storage/vector_evidence/schema.sql",
    "src/storage/vector_evidence/store.py",
    "tests/test_pgvector_schema_store_adapter_default_off.py",
    "tests/test_vector_evidence_service_pgvector_store_flagged_default_off.py",
    "tests/test_pgvector_store_db_executor_default_off.py",
    "tests/test_vector_evidence_service_db_executor_bridge_default_off.py",
    "src/storage/vector_evidence/connection.py",
    "tests/test_pgvector_connection_provider_default_off.py",
    "tests/test_vector_evidence_service_connection_provider_bridge_default_off.py",
    "src/storage/vector_evidence/smoke.py",
    "tests/test_pgvector_local_smoke_default_off.py",
    "src/storage/admin_tools/vector_evidence_pgvector_smoke.py",
    "tests/test_pgvector_real_local_smoke_command_default_off.py",
    "tests/test_pgvector_schema_executor_preserves_sql_newlines.py",
    "tests/test_pgvector_smoke_readback_verification_default_off.py",
    "tests/test_vector_evidence_readback_service_helper_default_off.py",
    "tests/test_vector_evidence_readback_api_default_off.py",
    "tests/test_vector_evidence_readback_ui_default_off.py",
    "src/agents/vector_evidence_pipeline_hook.py",
    "tests/test_pipeline_vector_evidence_hook_default_off.py",
    "tests/test_shadow_vector_evidence_context_default_off.py",
    "tests/test_shadow_agent_vector_evidence_input_default_off.py",
    "tests/test_shadow_semantic_evidence_agent_input_default_off.py",
    "src/storage/vector_evidence/embedding_provider.py",
    "tests/test_vector_evidence_embedding_provider_contract_default_off.py",
    "src/storage/vector_evidence/embedding_indexing.py",
    "tests/test_vector_evidence_embedding_indexing_helper_default_off.py",
    "src/storage/vector_evidence/embedding_retrieval.py",
    "tests/test_vector_evidence_embedding_retrieval_helper_default_off.py",
    "tests/test_pipeline_embedding_retrieval_hook_default_off.py",
    "src/storage/vector_evidence/embedding_runtime_adapter.py",
    "tests/test_vector_evidence_embedding_runtime_adapter_default_off.py",
    "tests/test_vector_evidence_embedding_runtime_service_bridge_default_off.py",
    "tests/test_pipeline_runtime_embedding_bridge_default_off.py",
    "src/agents/semantic_evidence_quality_gate.py",
    "tests/test_semantic_evidence_quality_gate_default_off.py",
    "tests/test_three_agent_shadow_workflow_default_off.py",
    "src/agents/agent_llmops_trace_contract.py",
    "tests/test_three_agent_llmops_trace_contract_default_off.py",
    "tests/test_jd_intelligence_provider_shadow_default_off.py",
    "tests/test_tailoring_provider_shadow_default_off.py",
    "tests/test_critic_provider_shadow_default_off.py",
    "tests/test_three_agent_provider_handoff_default_off.py",
    "src/agents/three_agent_llmops_aggregate.py",
    "tests/test_three_agent_llmops_aggregate_default_off.py",
    "src/agents/three_agent_workflow_readiness.py",
    "tests/test_three_agent_workflow_readiness_default_off.py",
    "src/agents/three_agent_llmops_observability_readback.py",
    "tests/test_three_agent_llmops_observability_readback_default_off.py",
    "tests/test_three_agent_llmops_observability_service_bridge_default_off.py",
    "tests/test_three_agent_llmops_observability_api_default_off.py",
    "tests/test_three_agent_llmops_observability_ui_default_off.py",
    "tests/test_phase10_llmops_observability_readiness_checkpoint.py",
    "src/agents/provider_runtime_readiness.py",
    "tests/test_provider_runtime_readiness_default_off.py",
    "src/agents/provider_runtime_adapter.py",
    "tests/test_provider_runtime_adapter_default_off.py",
    "tests/test_provider_runtime_shadow_bridge_default_off.py",
    "tests/test_provider_runtime_service_bridge_default_off.py",
    "tests/test_provider_runtime_api_readback_default_off.py",
    "tests/test_provider_runtime_ui_readback_default_off.py",
    "tests/test_provider_runtime_readiness_checkpoint_default_off.py",
    "src/agents/provider_runtime_activation_plan.py",
    "tests/test_provider_runtime_activation_plan_default_off.py",
    "src/agents/jd_provider_runtime_activation.py",
    "tests/test_jd_provider_runtime_activation_default_off.py",
    "tests/test_jd_provider_runtime_shadow_bridge_default_off.py",
    "src/agents/jd_provider_runtime_trace_readback.py",
    "tests/test_jd_provider_runtime_trace_readback_default_off.py",
    "tests/test_jd_provider_runtime_review_packet_default_off.py",
    "tests/test_jd_provider_runtime_service_readback_default_off.py",
    "tests/test_jd_provider_runtime_api_readback_default_off.py",
    "tests/test_jd_provider_runtime_ui_readback_default_off.py",
    "tests/test_jd_provider_runtime_readiness_checkpoint_default_off.py",
    "src/agents/provider_live_activation_safety_plan.py",
    "tests/test_provider_live_activation_safety_plan_default_off.py",
    "src/agents/provider_live_config_gate.py",
    "tests/test_provider_live_config_gate_default_off.py",
    "src/agents/jd_live_provider_canary.py",
    "tests/test_jd_live_provider_canary_default_off.py",
    "tests/test_jd_live_provider_canary_shadow_bridge_default_off.py",
    "src/agents/jd_live_provider_canary_readback.py",
    "tests/test_jd_live_provider_canary_readback_default_off.py",
    "tests/test_jd_live_provider_canary_service_readback_default_off.py",
    "tests/test_jd_live_provider_canary_api_readback_default_off.py",
    "tests/test_jd_live_provider_canary_ui_readback_default_off.py",
    "tests/test_jd_live_provider_canary_readiness_checkpoint_default_off.py",
    "src/agents/jd_live_provider_canary_command.py",
    "tests/test_jd_live_provider_canary_command_default_off.py",
    "src/agents/jd_live_provider_external_adapter.py",
    "tests/test_jd_live_provider_external_adapter_default_off.py",
    "src/agents/jd_live_provider_canary_runbook.py",
    "tests/test_jd_live_provider_canary_runbook_default_off.py",
    "tests/test_jd_manual_live_canary_readiness_checkpoint_default_off.py",
    "src/agents/jd_live_intelligence_expansion_plan.py",
    "tests/test_live_jd_intelligence_expansion_plan_default_off.py",
    "src/agents/jd_live_intelligence_review_readiness.py",
    "tests/test_live_jd_intelligence_review_readiness_default_off.py",
    "src/agents/jd_live_intelligence_evidence_review.py",
    "tests/test_live_jd_intelligence_evidence_review_default_off.py",
    "src/agents/jd_live_intelligence_operator_decision.py",
    "tests/test_live_jd_intelligence_operator_decision_default_off.py",
    "src/agents/jd_live_intelligence_approval_gate.py",
    "tests/test_live_jd_intelligence_approval_gate_default_off.py",
    "src/agents/jd_live_intelligence_rollout_handoff.py",
    "tests/test_live_jd_intelligence_rollout_handoff_default_off.py",
    "src/agents/jd_live_intelligence_phase_wrap.py",
    "tests/test_live_jd_intelligence_phase_wrap_default_off.py",
    "src/agents/jd_live_intelligence_runtime_readiness_plan.py",
    "tests/test_live_jd_intelligence_runtime_readiness_plan_default_off.py",
    "src/agents/jd_live_intelligence_runtime_preflight.py",
    "tests/test_live_jd_intelligence_runtime_preflight_default_off.py",
    "src/agents/three_core_agent_workflow_readiness.py",
    "tests/test_three_core_agent_workflow_readiness_default_off.py",
    "src/agents/three_core_agent_shadow_workflow_contract.py",
    "tests/test_three_core_agent_shadow_workflow_contract_default_off.py",
    "src/agents/three_core_agent_shadow_dry_run_packet.py",
    "tests/test_three_core_agent_shadow_dry_run_packet_default_off.py",
    "src/agents/three_core_agent_shadow_dry_run_readback.py",
    "tests/test_three_core_agent_shadow_dry_run_readback_default_off.py",
    "src/agents/three_core_agent_shadow_pipeline_connection_plan.py",
    "tests/test_three_core_agent_shadow_pipeline_connection_plan_default_off.py",
    "src/agents/three_core_agent_shadow_pipeline_hook.py",
    "tests/test_three_core_agent_shadow_pipeline_hook_default_off.py",
    "tests/test_three_core_agent_shadow_sidecar_bridge_default_off.py",
    "tests/test_three_core_agent_collector_shadow_wiring_default_off.py",
    "tests/test_three_core_agent_collector_connection_plan_default_off.py",
    "src/agents/three_core_agent_shadow_callable_adapters.py",
    "tests/test_three_core_agent_shadow_callable_adapters_default_off.py",
    "tests/test_three_core_agent_collector_callable_wiring_default_off.py",
    "src/agents/three_core_agent_shadow_runtime_readback.py",
    "tests/test_three_core_agent_shadow_runtime_readback_default_off.py",
    "src/agents/three_core_agent_shadow_operator_canary.py",
    "tests/test_three_core_agent_shadow_operator_canary_default_off.py",
    "tests/test_three_core_shadow_operator_canary_service_readback_default_off.py",
    "tests/test_three_core_shadow_operator_canary_api_readback_default_off.py",
    "tests/test_three_core_shadow_operator_canary_ui_readback_default_off.py",
    "tests/test_three_core_shadow_operator_canary_ui_fixture_visibility_default_off.py",
    "docs/three_core_shadow_readiness_wrap.md",
    "tests/test_three_core_shadow_readiness_wrap_default_off.py",
    "docs/phase18_live_readiness_approval_boundary.md",
    "tests/test_phase18_live_readiness_approval_boundary_default_off.py",
    "docs/phase18_human_approval_gate_contract.md",
    "tests/test_phase18_human_approval_gate_contract_default_off.py",
    "docs/phase18_approval_preview_readonly.md",
    "tests/test_phase18_approval_preview_readonly_default_off.py",
    "docs/phase18_operator_decision_capture_contract.md",
    "tests/test_phase18_operator_decision_capture_contract_default_off.py",
    "docs/phase18_live_provider_activation_plan.md",
    "tests/test_phase18_live_provider_activation_plan_default_off.py",
    "docs/phase18_provider_runtime_adapter_contract.md",
    "tests/test_phase18_provider_runtime_adapter_contract_default_off.py",
    "docs/phase18_live_provider_dry_run_packet_contract.md",
    "tests/test_phase18_live_provider_dry_run_packet_contract_default_off.py",
    "docs/phase18_provider_response_validation_contract.md",
    "tests/test_phase18_provider_response_validation_contract_default_off.py",
    "docs/phase18_provider_readback_audit_contract.md",
    "tests/test_phase18_provider_readback_audit_contract_default_off.py",
    "docs/phase18_provider_call_boundary_readiness_contract.md",
    "tests/test_phase18_provider_call_boundary_readiness_contract_default_off.py",
    "docs/phase18_mutation_boundary_readiness_contract.md",
    "tests/test_phase18_mutation_boundary_readiness_contract_default_off.py",
    "docs/phase18_safety_wrap_release_checkpoint.md",
    "tests/test_phase18_safety_wrap_release_checkpoint_default_off.py",
    "src/agents/three_core_approval_preview_runtime.py",
    "docs/phase19_approval_preview_runtime_readonly.md",
    "tests/test_phase19a_three_core_approval_preview_runtime_readonly_default_off.py",
    "src/agents/three_core_approval_preview_service_readback.py",
    "docs/phase19_approval_preview_service_readback.md",
    "tests/test_phase19b_three_core_approval_preview_service_readback_default_off.py",
    "docs/phase19_approval_preview_api_readback.md",
    "tests/test_phase19c_three_core_approval_preview_api_readback_default_off.py",
    "docs/phase19_approval_preview_ui_readback.md",
    "tests/test_phase19d_three_core_approval_preview_ui_readback_default_off.py",
    "docs/phase19_approval_preview_ui_api_fetch.md",
    "tests/test_phase19e_three_core_approval_preview_ui_api_fetch_default_off.py",
    "docs/phase19_approval_preview_operator_decision_preview.md",
    "tests/test_phase19f_approval_preview_operator_decision_preview_default_off.py",
    "src/agents/operator_decision_capture_readback_contract.py",
    "docs/phase19_operator_decision_capture_readback_contract.md",
    "tests/test_phase19g_operator_decision_capture_readback_contract_default_off.py",
    "docs/phase19_operator_decision_capture_api_readback.md",
    "tests/test_phase19h_operator_decision_capture_api_readback_default_off.py",
    "docs/phase19_operator_decision_capture_ui_readback.md",
    "tests/test_phase19i_operator_decision_capture_ui_readback_default_off.py",
    "docs/phase19_readonly_approval_workflow_release_checkpoint.md",
    "tests/test_phase19j_readonly_approval_workflow_release_checkpoint_default_off.py",
    "src/agents/provider_call_readiness_experiment.py",
    "docs/phase20_provider_call_readiness_experiment.md",
    "tests/test_phase20a_provider_call_readiness_experiment_default_off.py",
    "src/app/api.py",
    "docs/phase20_provider_call_readiness_api_readback.md",
    "tests/test_phase20b_provider_call_readiness_api_readback_default_off.py",
    "docs/phase20_provider_call_readiness_ui_readback.md",
    "tests/test_phase20c_provider_call_readiness_ui_readback_default_off.py",
    "docs/no_auto_apply_safety_policy.md",
    "docs/phase20_no_auto_apply_safety_checkpoint.md",
    "tests/test_phase20d_no_auto_apply_safety_checkpoint_default_off.py",
    "docs/phase20_provider_readiness_release_checkpoint.md",
    "tests/test_phase20e_provider_readiness_release_checkpoint_default_off.py",
    "docs/manual_review_workflow_boundary.md",
    "docs/phase21_manual_review_workflow_boundary.md",
    "tests/test_phase21a_manual_review_workflow_boundary_default_off.py",
    "src/agents/manual_review_readiness_contract.py",
    "docs/phase21_manual_review_readiness_contract.md",
    "tests/test_phase21b_manual_review_readiness_contract_default_off.py",
    "docs/phase21_manual_review_readiness_api_readback.md",
    "tests/test_phase21c_manual_review_readiness_api_readback_default_off.py",
    "docs/phase21_manual_review_readiness_ui_readback.md",
    "tests/test_phase21d_manual_review_readiness_ui_readback_default_off.py",
    "docs/phase21_manual_review_workflow_release_checkpoint.md",
    "tests/test_phase21e_manual_review_workflow_release_checkpoint_default_off.py",
    "docs/phase22_manual_review_ux_hardening.md",
    "tests/test_phase22a_manual_review_ux_hardening_default_off.py",
}

def _changed_files():
    tracked = subprocess.check_output(["git", "diff", "--name-only"], cwd=ROOT, text=True).splitlines()
    untracked = subprocess.check_output(
        ["git", "ls-files", "--others", "--exclude-standard"],
        cwd=ROOT,
        text=True,
    ).splitlines()
    return set(tracked + untracked)

def test_portfolio_demo_readiness_doc_exists_and_has_required_terms():
    assert DOC.exists()
    text = DOC.read_text()
    missing = [term for term in REQUIRED_TERMS if term not in text]
    assert not missing

def test_portfolio_demo_readiness_doc_is_linked():
    link = "docs/portfolio_demo_readiness_wrap_checkpoint.md"
    assert link in (ROOT / "README.md").read_text()
    assert link in (ROOT / "docs/orchestrator_readiness.md").read_text()

def test_portfolio_demo_readiness_is_docs_tests_only():
    changed = _changed_files() - {
        "docs/core_agent_automation_mutation_inventory.md",
        "docs/phase22_core_agent_automation_mutation_inventory.md",
        "src/agents/core_agent_evidence_materialization_preview.py",
        "docs/phase22_core_agent_evidence_materialization_preview.md",
        "tests/test_phase22c_core_agent_evidence_materialization_preview_default_off.py",
        "src/app/api.py",
        "docs/phase22_core_agent_evidence_materialization_api_readback.md",
        "tests/test_phase22d_core_agent_evidence_materialization_api_readback_default_off.py",
        "src/app/static/agentic_review.js",
        "src/app/static/app_redesign.css",
        "docs/phase22_core_agent_evidence_materialization_ui_readback.md",
        "tests/test_phase22e_core_agent_evidence_materialization_ui_readback_default_off.py",
        "docs/phase22_core_agent_evidence_materialization_release_checkpoint.md",
        "tests/test_phase22f_core_agent_evidence_materialization_release_checkpoint_default_off.py",
        "src/agents/tailoring_agent_opportunity_contract.py",
        "docs/phase23_tailoring_agent_opportunity_contract.md",
        "tests/test_phase23a_tailoring_agent_opportunity_contract_default_off.py",
        "docs/phase23_tailoring_agent_opportunity_api_readback.md",
        "tests/test_phase23b_tailoring_agent_opportunity_api_readback_default_off.py",
        "docs/phase23_tailoring_agent_opportunity_ui_readback.md",
        "tests/test_phase23c_tailoring_agent_opportunity_ui_readback_default_off.py",
        "src/agents/generate_ai_tailoring_action_boundary_contract.py",
        "docs/phase23_generate_ai_tailoring_action_boundary_contract.md",
        "tests/test_phase23d_generate_ai_tailoring_action_boundary_contract_default_off.py",
        "docs/phase23_generate_ai_tailoring_action_boundary_api_readback.md",
        "tests/test_phase23e_generate_ai_tailoring_action_boundary_api_readback_default_off.py",
        "docs/phase23_generate_ai_tailoring_action_boundary_ui_readback.md",
        "tests/test_phase23f_generate_ai_tailoring_action_boundary_ui_readback_default_off.py",
        "docs/phase23_tailoring_agent_workflow_release_checkpoint.md",
        "tests/test_phase23g_tailoring_agent_workflow_release_checkpoint_default_off.py",
        "src/agents/manual_generate_ai_tailoring_preview_contract.py",
        "docs/phase24_manual_generate_ai_tailoring_preview_contract.md",
        "tests/test_phase24a_manual_generate_ai_tailoring_preview_contract_default_off.py",
        "docs/phase24_manual_generate_ai_tailoring_preview_api_readback.md",
        "tests/test_phase24b_manual_generate_ai_tailoring_preview_api_readback_default_off.py",
        "src/app/static/agentic_review.js",
        "src/app/static/app_redesign.css",
        "docs/phase24_manual_generate_ai_tailoring_preview_ui_readback.md",
        "tests/test_phase24c_manual_generate_ai_tailoring_preview_ui_readback_default_off.py",
        "docs/phase24_manual_generate_ai_tailoring_preview_release_checkpoint.md",
        "tests/test_phase24d_manual_generate_ai_tailoring_preview_release_checkpoint_default_off.py",
            "src/agents/manual_generate_ai_tailoring_preview_request_packet_contract.py",
            "docs/phase25_manual_generate_ai_tailoring_preview_request_packet_contract.md",
            "tests/test_phase25a_manual_generate_ai_tailoring_preview_request_packet_contract_default_off.py",
            "docs/phase25_manual_generate_ai_tailoring_preview_request_packet_api_readback.md",
            "tests/test_phase25b_manual_generate_ai_tailoring_preview_request_packet_api_readback_default_off.py",
            "src/app/static/agentic_review.js",
            "src/app/static/app_redesign.css",
            "docs/phase25_manual_generate_ai_tailoring_preview_request_packet_ui_readback.md",
            "tests/test_phase25c_manual_generate_ai_tailoring_preview_request_packet_ui_readback_default_off.py",
            "docs/phase25_manual_generate_ai_tailoring_preview_request_packet_release_checkpoint.md",
            "tests/test_phase25d_manual_generate_ai_tailoring_preview_request_packet_release_checkpoint_default_off.py",
            "src/agents/manual_generate_ai_tailoring_preview_dispatch_boundary_contract.py",
            "docs/phase26_manual_generate_ai_tailoring_preview_dispatch_boundary_contract.md",
            "tests/test_phase26a_manual_generate_ai_tailoring_preview_dispatch_boundary_contract_default_off.py",
            "src/app/api.py",
            "docs/phase26_manual_generate_ai_tailoring_preview_dispatch_boundary_api_readback.md",
            "tests/test_phase26b_manual_generate_ai_tailoring_preview_dispatch_boundary_api_readback_default_off.py",
            "src/app/static/agentic_review.js",
            "src/app/static/app_redesign.css",
            "docs/phase26_manual_generate_ai_tailoring_preview_dispatch_boundary_ui_readback.md",
            "tests/test_phase26c_manual_generate_ai_tailoring_preview_dispatch_boundary_ui_readback_default_off.py",
            "docs/phase26_manual_generate_ai_tailoring_preview_dispatch_boundary_release_checkpoint.md",
            "tests/test_phase26d_manual_generate_ai_tailoring_preview_dispatch_boundary_release_checkpoint_default_off.py",
            "src/agents/manual_generate_ai_tailoring_preview_provider_request_envelope_contract.py",
            "docs/phase27_manual_generate_ai_tailoring_preview_provider_request_envelope_contract.md",
            "tests/test_phase27a_manual_generate_ai_tailoring_preview_provider_request_envelope_contract_default_off.py",
            "src/app/api.py",
            "docs/phase27_manual_generate_ai_tailoring_preview_provider_request_envelope_api_readback.md",
            "tests/test_phase27b_manual_generate_ai_tailoring_preview_provider_request_envelope_api_readback_default_off.py",
            "src/app/static/agentic_review.js",
            "src/app/static/app_redesign.css",
            "docs/phase27_manual_generate_ai_tailoring_preview_provider_request_envelope_ui_readback.md",
            "tests/test_phase27c_manual_generate_ai_tailoring_preview_provider_request_envelope_ui_readback_default_off.py",
            "docs/phase27_manual_generate_ai_tailoring_preview_provider_request_envelope_release_checkpoint.md",
            "tests/test_phase27d_manual_generate_ai_tailoring_preview_provider_request_envelope_release_checkpoint_default_off.py",
            "src/agents/manual_generate_ai_tailoring_preview_provider_call_boundary_contract.py",
            "docs/phase28_manual_generate_ai_tailoring_preview_provider_call_boundary_contract.md",
            "tests/test_phase28a_manual_generate_ai_tailoring_preview_provider_call_boundary_contract_default_off.py",
            "src/app/api.py",
            "docs/phase28_manual_generate_ai_tailoring_preview_provider_call_boundary_api_readback.md",
            "tests/test_phase28b_manual_generate_ai_tailoring_preview_provider_call_boundary_api_readback_default_off.py",
            "src/app/static/agentic_review.js",
            "src/app/static/app_redesign.css",
            "docs/phase28_manual_generate_ai_tailoring_preview_provider_call_boundary_ui_readback.md",
            "tests/test_phase28c_manual_generate_ai_tailoring_preview_provider_call_boundary_ui_readback_default_off.py",
            "docs/phase28_manual_generate_ai_tailoring_preview_provider_call_boundary_ui_readback 2.md",
            "tests/test_phase28c_manual_generate_ai_tailoring_preview_provider_call_boundary_ui_readback_default_off 2.py",
            "docs/phase28_manual_generate_ai_tailoring_preview_provider_call_boundary_release_checkpoint.md",
            "tests/test_phase28d_manual_generate_ai_tailoring_preview_provider_call_boundary_release_checkpoint_default_off.py",
            "src/agents/manual_generate_ai_tailoring_preview_provider_call_dry_run_packet_contract.py",
            "docs/phase29_manual_generate_ai_tailoring_preview_provider_call_dry_run_packet_contract.md",
            "tests/test_phase29a_manual_generate_ai_tailoring_preview_provider_call_dry_run_packet_contract_default_off.py",
            "src/app/api.py",
            "docs/phase29_manual_generate_ai_tailoring_preview_provider_call_dry_run_packet_api_readback.md",
            "tests/test_phase29b_manual_generate_ai_tailoring_preview_provider_call_dry_run_packet_api_readback_default_off.py",
            "src/app/static/agentic_review.js",
            "src/app/static/app_redesign.css",
            "docs/phase29_manual_generate_ai_tailoring_preview_provider_call_dry_run_packet_ui_readback.md",
            "tests/test_phase29c_manual_generate_ai_tailoring_preview_provider_call_dry_run_packet_ui_readback_default_off.py",
            "docs/phase29_manual_generate_ai_tailoring_preview_provider_call_dry_run_packet_release_checkpoint.md",
            "tests/test_phase29d_manual_generate_ai_tailoring_preview_provider_call_dry_run_packet_release_checkpoint_default_off.py",
            "src/agents/manual_generate_ai_tailoring_preview_provider_response_validation_contract.py",
            "docs/phase30_manual_generate_ai_tailoring_preview_provider_response_validation_contract.md",
            "tests/test_phase30a_manual_generate_ai_tailoring_preview_provider_response_validation_contract_default_off.py",
            "src/app/api.py",
            "docs/phase30_manual_generate_ai_tailoring_preview_provider_response_validation_api_readback.md",
            "tests/test_phase30b_manual_generate_ai_tailoring_preview_provider_response_validation_api_readback_default_off.py",
                "src/app/static/agentic_review.js",
                "src/app/static/app_redesign.css",
                "docs/phase30_manual_generate_ai_tailoring_preview_provider_response_validation_ui_readback.md",
                "tests/test_phase30c_manual_generate_ai_tailoring_preview_provider_response_validation_ui_readback_default_off.py",
                    "docs/phase30_manual_generate_ai_tailoring_preview_provider_response_validation_release_checkpoint.md",
                    "tests/test_phase30d_manual_generate_ai_tailoring_preview_provider_response_validation_release_checkpoint_default_off.py",
                        "src/agents/manual_generate_ai_tailoring_preview_provider_response_normalization_contract.py",
                        "docs/phase31_manual_generate_ai_tailoring_preview_provider_response_normalization_contract.md",
                        "tests/test_phase31a_manual_generate_ai_tailoring_preview_provider_response_normalization_contract_default_off.py",
                        "src/app/api.py",
                        "docs/phase31_manual_generate_ai_tailoring_preview_provider_response_normalization_api_readback.md",
                        "tests/test_phase31b_manual_generate_ai_tailoring_preview_provider_response_normalization_api_readback_default_off.py",
                            "docs/phase31_manual_generate_ai_tailoring_preview_provider_response_normalization_ui_readback.md",
                            "tests/test_phase31c_manual_generate_ai_tailoring_preview_provider_response_normalization_ui_readback_default_off.py",
                                "docs/phase31_manual_generate_ai_tailoring_preview_provider_response_normalization_release_checkpoint.md",
                                "tests/test_phase31d_manual_generate_ai_tailoring_preview_provider_response_normalization_release_checkpoint_default_off.py",
                                "src/agents/manual_generate_ai_tailoring_preview_normalized_response_preview_packet_contract.py",
                                "docs/phase32_manual_generate_ai_tailoring_preview_normalized_response_preview_packet_contract.md",
                                "tests/test_phase32a_manual_generate_ai_tailoring_preview_normalized_response_preview_packet_contract_default_off.py",
                                "src/app/api.py",
                                "docs/phase32_manual_generate_ai_tailoring_preview_normalized_response_preview_packet_api_readback.md",
                                "tests/test_phase32b_manual_generate_ai_tailoring_preview_normalized_response_preview_packet_api_readback_default_off.py",
                                "docs/phase32_manual_generate_ai_tailoring_preview_normalized_response_preview_packet_api_readback 2.md",
                                "tests/test_phase32b_manual_generate_ai_tailoring_preview_normalized_response_preview_packet_api_readback_default_off 2.py",
                                "src/agents/controlled_agent_router_readonly.py",
                                "docs/phase33_controlled_agent_router_readonly.md",
                                "tests/test_phase33a_controlled_agent_router_readonly.py",
                                "docs/phase33_controlled_agent_router_readonly 2.md",
                                "tests/test_phase33a_controlled_agent_router_readonly 2.py",
                                "src/agents/controlled_agent_router_workflow_state_adapter_readonly.py",
                                "docs/phase33_controlled_agent_router_workflow_state_adapter_readonly.md",
                                "tests/test_phase33b_controlled_agent_router_workflow_state_adapter_readonly.py",
                                "src/agents/controlled_agent_router_batch_handoff_plan_readonly.py",
                                "docs/phase33_controlled_agent_router_batch_handoff_plan_readonly.md",
                                "tests/test_phase33c_controlled_agent_router_batch_handoff_plan_readonly.py",
                                "src/agents/controlled_agent_router_planning_artifact_mapper_readonly.py",
                                "docs/phase33_controlled_agent_router_planning_artifact_mapper_readonly.md",
                                "tests/test_phase33d_controlled_agent_router_planning_artifact_mapper_readonly.py",
                                "run_controlled_agent_router_planning_artifact_dry_run.py",
                                "docs/phase33_controlled_agent_router_planning_artifact_dry_run_command_readonly.md",
                                "tests/test_phase33e_controlled_agent_router_planning_artifact_dry_run_command_readonly.py",
                                "src/agents/jd_intelligence_llm_signal_extractor_default_off.py",
                                "docs/phase34_jd_intelligence_llm_signal_extractor_default_off.md",
                                "tests/test_phase34a_jd_intelligence_llm_signal_extractor_default_off.py",
                                "src/agents/jd_intelligence_planning_artifact_enricher_default_off.py",
                                "docs/phase34_jd_intelligence_planning_artifact_enricher_default_off.md",
                                "tests/test_phase34b_jd_intelligence_planning_artifact_enricher_default_off.py",
                                "run_jd_intelligence_planning_artifact_enrichment_dry_run.py",
                                "docs/phase34_jd_intelligence_planning_artifact_enrichment_dry_run_command_default_off.md",
                                "tests/test_phase34c_jd_intelligence_planning_artifact_enrichment_dry_run_command_default_off.py",
                                "src/agents/jd_signal_resume_evidence_matrix_default_off.py",
                                "docs/phase35_jd_signal_resume_evidence_matrix_default_off.md",
                                "tests/test_phase35a_jd_signal_resume_evidence_matrix_default_off.py",
                                "src/agents/jd_signal_planning_artifact_evidence_enricher_default_off.py",
                                "docs/phase35_jd_signal_planning_artifact_evidence_enricher_default_off.md",
                                "tests/test_phase35b_jd_signal_planning_artifact_evidence_enricher_default_off.py",
                                "run_jd_signal_planning_artifact_evidence_enrichment_dry_run.py",
                                "docs/phase35_jd_signal_planning_artifact_evidence_enrichment_dry_run_command_default_off.md",
                                "tests/test_phase35c_jd_signal_planning_artifact_evidence_enrichment_dry_run_command_default_off.py",
                                "src/agents/jd_evidence_final_scoring_feature_adapter_default_off.py",
                                "docs/phase36_jd_evidence_final_scoring_feature_adapter_default_off.md",
                                "tests/test_phase36a_jd_evidence_final_scoring_feature_adapter_default_off.py",
                                "run_jd_evidence_final_scoring_feature_adapter_dry_run.py",
                                "docs/phase36_jd_evidence_final_scoring_feature_adapter_dry_run_command_default_off.md",
                                "tests/test_phase36b_jd_evidence_final_scoring_feature_adapter_dry_run_command_default_off.py",
                                "src/agents/jd_evidence_scoring_contribution_preview_default_off.py",
                                "docs/phase37_jd_evidence_scoring_contribution_preview_default_off.md",
                                "tests/test_phase37a_jd_evidence_scoring_contribution_preview_default_off.py",
                                "run_jd_evidence_scoring_contribution_preview_dry_run.py",
                                "docs/phase37_jd_evidence_scoring_contribution_preview_dry_run_command_default_off.md",
                                "tests/test_phase37b_jd_evidence_scoring_contribution_preview_dry_run_command_default_off.py",
                                "src/agents/jd_evidence_score_impact_preview_default_off.py",
                                "docs/phase38_jd_evidence_score_impact_preview_default_off.md",
                                "tests/test_phase38a_jd_evidence_score_impact_preview_default_off.py",
                                "tests/test_phase38a_jd_evidence_score_impact_preview_default_off 2.py",
                                "\"tests/test_phase38a_jd_evidence_score_impact_preview_default_off 2.py\"",
                                "run_jd_evidence_score_impact_preview_dry_run.py",
                                "docs/phase38_jd_evidence_score_impact_preview_dry_run_command_default_off.md",
                                "tests/test_phase38b_jd_evidence_score_impact_preview_dry_run_command_default_off.py",
                                "src/agents/jd_evidence_score_impact_planning_artifact_annotator_default_off.py",
                                "docs/phase39_jd_evidence_score_impact_planning_artifact_annotator_default_off.md",
                                "tests/test_phase39a_jd_evidence_score_impact_planning_artifact_annotator_default_off.py",
                                "run_jd_evidence_score_impact_planning_artifact_annotator_dry_run.py",
                                "docs/phase39_jd_evidence_score_impact_planning_artifact_annotator_dry_run_command_default_off.md",
                                "tests/test_phase39b_jd_evidence_score_impact_planning_artifact_annotator_dry_run_command_default_off.py",
                                "src/agents/jd_evidence_score_impact_review_packet_builder_default_off.py",
                                "docs/phase40_jd_evidence_score_impact_review_packet_builder_default_off.md",
                                "tests/test_phase40a_jd_evidence_score_impact_review_packet_builder_default_off.py",
                                "run_jd_evidence_score_impact_review_packet_builder_dry_run.py",
                                "docs/phase40_jd_evidence_score_impact_review_packet_builder_dry_run_command_default_off.md",
                                "tests/test_phase40b_jd_evidence_score_impact_review_packet_builder_dry_run_command_default_off.py",
                                "src/agents/jd_evidence_score_impact_review_queue_builder_default_off.py",
                                "docs/phase41_jd_evidence_score_impact_review_queue_builder_default_off.md",
                                "src/agents/exact_resume_change_set_proposal_builder_default_off.py",
                                "docs/phase42_exact_resume_change_set_proposal_builder_default_off.md",
                                "src/agents/controlled_exact_resume_change_set_llm_request_packet_default_off.py",
                                "docs/phase43_controlled_exact_resume_change_set_llm_request_packet_default_off.md",
                                "src/agents/controlled_exact_resume_change_set_provider_call_boundary_default_off.py",
                                "docs/phase44_controlled_exact_resume_change_set_provider_call_boundary_default_off.md",
                                "run_controlled_exact_resume_change_set_provider_call_boundary_dry_run.py",
                                "docs/phase44_controlled_exact_resume_change_set_provider_call_boundary_dry_run_command_default_off.md",
                                "tests/test_phase44b_controlled_exact_resume_change_set_provider_call_boundary_dry_run_command_default_off.py",
                "src/agents/controlled_exact_resume_change_set_provider_response_validation_default_off.py",
                "docs/phase45_controlled_exact_resume_change_set_provider_response_validation_default_off.md",
                "tests/test_phase45a_controlled_exact_resume_change_set_provider_response_validation_default_off.py",
                "run_controlled_exact_resume_change_set_provider_response_validation_dry_run.py",
                "docs/phase45_controlled_exact_resume_change_set_provider_response_validation_dry_run_command_default_off.md",
                "tests/test_phase45b_controlled_exact_resume_change_set_provider_response_validation_dry_run_command_default_off.py",
                "src/agents/controlled_exact_resume_change_set_provider_response_normalization_default_off.py",
                "docs/phase46_controlled_exact_resume_change_set_provider_response_normalization_default_off.md",
                "tests/test_phase46a_controlled_exact_resume_change_set_provider_response_normalization_default_off.py",
                                "tests/test_phase44a_controlled_exact_resume_change_set_provider_call_boundary_default_off.py",
                                "run_controlled_exact_resume_change_set_llm_request_packet_dry_run.py",
                                "docs/phase43_controlled_exact_resume_change_set_llm_request_packet_dry_run_command_default_off.md",
                                "tests/test_phase43b_controlled_exact_resume_change_set_llm_request_packet_dry_run_command_default_off.py",
                                "tests/test_phase43a_controlled_exact_resume_change_set_llm_request_packet_default_off.py",
                                "run_exact_resume_change_set_proposal_builder_dry_run.py",
                                "docs/phase42_exact_resume_change_set_proposal_builder_dry_run_command_default_off.md",
                                "tests/test_phase42b_exact_resume_change_set_proposal_builder_dry_run_command_default_off.py",
                                "tests/test_phase42a_exact_resume_change_set_proposal_builder_default_off.py",
                                "run_jd_evidence_score_impact_review_queue_builder_dry_run.py",
                                "docs/phase41_jd_evidence_score_impact_review_queue_builder_dry_run_command_default_off.md",
                                "tests/test_phase41b_jd_evidence_score_impact_review_queue_builder_dry_run_command_default_off.py",
                                "tests/test_phase41a_jd_evidence_score_impact_review_queue_builder_default_off.py",
        "docs/phase23_generate_ai_tailoring_action_boundary_api_readback 2.md",
        "tests/test_phase23e_generate_ai_tailoring_action_boundary_api_readback_default_off 2.py",
        "docs/phase22_core_agent_evidence_materialization_api_readback 2.md",
        "tests/test_phase22d_core_agent_evidence_materialization_api_readback_default_off 2.py",
    }
    legacy_static_hash_guards = {
        str(path.relative_to(ROOT))
        for path in (ROOT / "tests").glob("test_*.py")
        if path.name == "test_three_core_agent_shadow_sidecar_bridge_default_off.py"
        or any(
            marker in path.read_text(encoding="utf-8")
            for marker in (
                "c0c7a0a229a0cc9a1042c84c37a1728a33707e1035f6d604b6fe6aa74cc4b5e7",
                "62429a0e1466a93869e303023b6ee9a23108db6dddfd3b2c2247b2d31062169c",
                "300bd7285e7ed258197432f74cdab390f11f61670e5ef8e0feb77e3e90c005ab",
            )
        )
    }
    extra = sorted(
        path
        for path in changed
        if path not in ALLOWED_CHANGED
        and path not in legacy_static_hash_guards
    )
    assert not extra

    approved_runtime_paths = {
        "src/app/api.py",
        "src/app/services.py",
        "src/app/static/agentic_review.js",
        "src/app/static/app_redesign.css",
        "src/storage/agent_trace/store.py",
        "src/agents/trace.py",
        "src/agents/relevance_prefilter.py",
        "src/agents/deduplication.py",
        "src/agents/jd_intelligence.py",
        "src/agents/final_application_scoring.py",
        "src/agents/resume_match_agent.py",
        "src/agents/tailoring_decision_agent.py",
        "src/agents/critic_agent.py",
        "src/agents/job_prioritization_agent.py",
        "src/agents/shadow_sidecar.py",
        "src/agents/shadow_sidecar_hook.py",
        "src/agents/shadow_sidecar_trace_persistence.py",
        "src/agents/shadow_sidecar_trace_readback.py",
        "src/agents/shadow_sidecar_evidence_snapshot.py",
        "src/agents/shadow_sidecar_score_comparison.py",
        "src/agents/human_reviewed_influence_preview.py",
        "src/agents/agent_recommendation_overlay.py",
        "src/agents/agent_recommendation_overlay_readback.py",
        "src/agents/agent_recommendation_overlay_readiness.py",
        "src/agents/pipeline_agent_review_packet.py",
        "src/agents/vector_evidence_contract.py",
        "src/agents/vector_evidence_indexing_dry_run.py",
        "src/agents/vector_evidence_retrieval_dry_run.py",
        "src/agents/pgvector_extension_probe.py",
        "src/agents/vector_evidence_pipeline_hook.py",
        "src/agents/semantic_evidence_quality_gate.py",
        "src/agents/agent_llmops_trace_contract.py",
        "src/agents/three_agent_llmops_aggregate.py",
        "src/agents/three_agent_workflow_readiness.py",
        "src/agents/three_agent_llmops_observability_readback.py",
        "src/agents/provider_runtime_readiness.py",
        "src/agents/provider_runtime_adapter.py",
        "src/agents/provider_runtime_activation_plan.py",
        "src/agents/jd_provider_runtime_activation.py",
        "src/agents/jd_provider_runtime_trace_readback.py",
        "src/agents/provider_live_activation_safety_plan.py",
        "src/agents/provider_live_config_gate.py",
        "src/agents/jd_live_provider_canary.py",
        "src/agents/jd_live_provider_canary_readback.py",
        "src/agents/jd_live_provider_canary_command.py",
        "src/agents/jd_live_provider_external_adapter.py",
        "src/agents/jd_live_provider_canary_runbook.py",
        "src/agents/jd_live_intelligence_expansion_plan.py",
        "src/agents/jd_live_intelligence_review_readiness.py",
        "src/agents/jd_live_intelligence_evidence_review.py",
        "src/agents/jd_live_intelligence_operator_decision.py",
        "src/agents/jd_live_intelligence_approval_gate.py",
        "src/agents/jd_live_intelligence_rollout_handoff.py",
        "src/agents/jd_live_intelligence_phase_wrap.py",
        "src/agents/jd_live_intelligence_runtime_readiness_plan.py",
        "src/agents/jd_live_intelligence_runtime_preflight.py",
        "src/agents/three_core_agent_workflow_readiness.py",
        "src/agents/three_core_agent_shadow_workflow_contract.py",
        "src/agents/three_core_agent_shadow_dry_run_packet.py",
        "src/agents/three_core_agent_shadow_dry_run_readback.py",
        "src/agents/three_core_agent_shadow_pipeline_connection_plan.py",
        "src/agents/three_core_agent_shadow_pipeline_hook.py",
        "src/agents/three_core_agent_shadow_callable_adapters.py",
        "src/agents/three_core_agent_shadow_runtime_readback.py",
        "src/agents/three_core_agent_shadow_operator_canary.py",
            "src/agents/three_core_approval_preview_runtime.py",
            "src/agents/three_core_approval_preview_service_readback.py",
            "src/agents/operator_decision_capture_readback_contract.py",
            "src/agents/provider_call_readiness_experiment.py",
            "src/agents/manual_review_readiness_contract.py",
            "src/storage/vector_evidence/__init__.py",
        "src/storage/vector_evidence/schema.sql",
        "src/storage/vector_evidence/store.py",
        "src/storage/vector_evidence/connection.py",
        "src/storage/vector_evidence/smoke.py",
        "src/storage/vector_evidence/embedding_provider.py",
        "src/storage/vector_evidence/embedding_indexing.py",
        "src/storage/vector_evidence/embedding_retrieval.py",
        "src/storage/vector_evidence/embedding_runtime_adapter.py",
        "src/storage/admin_tools/vector_evidence_pgvector_smoke.py",
        "src/pipeline/collector.py",
    }
    runtime_paths = [
        path for path in changed
        if path not in approved_runtime_paths
        and (
            path.startswith("src/")
            or path == "application_execution_queue.py"
            or path.endswith(".js")
            or path.endswith(".html")
            or path.endswith(".css")
        )
    ]
    assert not runtime_paths
